const dataNumber = 2;
console.log(`Number = ${dataNumber}`);
const dataBoolean = true;
console.log(`Boolean = ${dataBoolean}`);
let dataUndefined;
console.log(`Undefined = ${dataUndefined}`);
const dataNull = null;
console.log(`Null = ${dataNull}`);
const dataString = 'AmazingJS';
console.log(`String = ${dataString}`);
